### ISSUE TITLE
Proof Key for Code Exchange is required for cross-origin authorization code redemption.

### ISSUE THREAD

**Issue by kishanappringer** [microsoftgraph/msgraph-sdk-php#1057]
Hi Team, 
I'm getting "invalid_request" error when I clone and set it to code "https://github.com/microsoftgraph/msgraph-sample-phpapp.git" in my system 
![Screenshot from 2022-11-04 15-04-30](https://user-images.githubusercontent.com/107383884/199941159-7e1dbecc-782e-4dba-98fa-911ed8073dca.png)

Thanks
Kishan

**Comment by Ndiritu** [comment]
@kishanappringer looks like this might have something to do with registering your redirect URIs as an [SPA instead of Web](https://stackoverflow.com/questions/64692600/aadsts9002325-proof-key-for-code-exchange-is-required-for-cross-origin-authoriz)

Please consider submitting your issue to the relevant repo (https://github.com/microsoftgraph/msgraph-sample-phpapp.git) as this is not an SDK issue

**Comment by kishanappringer** [comment]
ok Thanks
