### ISSUE TITLE
Beta Dependencies in GA

### ISSUE THREAD

**Issue by shemogumbe** [microsoftgraph/msgraph-sdk-php#1112]
Would it be a good idea to use a dependency at Beta for a GA release. The [dependency](https://github.com/open-telemetry/opentelemetry-php)

**Comment by shemogumbe** [comment]
For telemetry tracing in PHP, we are currently using this library [Open telemetry] (https://github.com/open-telemetry/opentelemetry-php).
The library is currently in Beta, and advises that for long term support we specify dev releases, not even the latest version (Beta)

While it might not be a good idea to use a Beta Library to use dependencies that are not on general availability due to potential breaking changes and quality issues, there seem to be no other alternatives at this time. 

Could we take this approach for this particular case. cc @MIchaelMainer @darrelmiller @baywet @ddyett

**Comment by baywet** [comment]
Thanks for flagging this Shem.
While we should always be cautious about using anything non GA as a dependency since it will impact our own ability to support our customers, I think this one is fine for a couple of reasons:
- it implements a standard, which reduces their ability to drastically change the library API surface (has to map to the concepts of the standard).
- the way it's been implemented in dotnet/go/typescript/java is limited the the kiota abstractions/http/authentication libraries, and it's encapsulated. Should a breaking change arise, we should be able to change our implementation code, and minor or patch bump without impacting the customers experience.

Throughts?

**Comment by MIchaelMainer** [comment]
+1 to what Vincent said.

If the customer is concerned with capturing traces using OpenTelemetry, they may likely be tracing other parts of their application that are not using MG so they should be aware of the beta quality bar for PHP OpenTelemetry. If a breaking change occurs, it will likely impact their application code at the same time as our SDK code.  

We should make a note somewhere that we implement OpenTelemetry and that our current instrumentation is based on beta versions of OpenTelemetry for PHP.

**Comment by Ndiritu** [comment]
closing since implementation will be tracked under https://github.com/microsoft/kiota/issues/1871
