### ISSUE TITLE
Remove docs and tests from composer 

### ISSUE THREAD

**Issue by MarkehMe** [microsoftgraph/msgraph-sdk-php#13]
The docs and tests combined bring the composer package to 33.9MB. **33.2MB alone is just docs**.

Being in the vendor folder, this generally isn't read. It's also extremely unnecessary when packaged and distributed.

97% of the msgraph-sdk-php package is docs, which aren't read as a composer package.

**Comment by noahheck** [comment]
The docs for Zend Framework components are managed within the same repo as the component itself, but are prevented from being distributed via composer using `export-ignore` in the `.gitattributes` file: https://github.com/zendframework/zend-http/blob/master/.gitattributes

Git .gitattributes docs: https://www.kernel.org/pub/software/scm/git/docs/gitattributes.html

Symfony, by contrast, keeps all of the documentation in a separate repo: https://github.com/symfony/symfony-docs

Since the documentation for the SDK seems to be auto-generated, it might be easier to exclude using the `.gitattributes` method.

---

On the other hand, I believe the tests should be distributed with the software.

**Comment by MarkehMe** [comment]
Sure, I can see reasons for the tests being there. The test aren't very big so that not a huge concern 😄 

But the docs on the other hand make the sdk a lot bigger than it needs to be.

@cbales being the only contributor - could this be done, would you accept a pull request for this?

**Comment by cbales** [comment]
I definitely agree that the docs shouldn't be included in the package; that was a mistake on my part. I'll get those removed from the package using Noah's suggestion. Thanks for finding this!

**Comment by cbales** [comment]
I'll pull this change in with the next release of the library

**Comment by noahheck** [comment]
Brought the total disk used down to < 800kB :+1:

**Comment by MarkehMe** [comment]
Thanks so much!
