### ISSUE TITLE
API: Each individual day must have its own startTime and endTime.

### ISSUE THREAD

**Issue by EddieTerpan** [microsoftgraph/msgraph-sdk-php#1457]
Each individual day must have its own startTime and endTime. It is unclear how this can be used now and for what. Moreover, it also works strangely.

Please add startTime and endTime for each day.

https://learn.microsoft.com/en-us/graph/api/user-get-mailboxsettings?view=graph-rest-1.0&tabs=http
https://learn.microsoft.com/en-us/graph/api/calendar-getschedule?view=graph-rest-1.0&tabs=http

responce:
```
...
"workingHours":{
        "daysOfWeek":[
            "monday",
            "tuesday",
            "wednesday",
            "thursday",
            "friday"
        ],
        "startTime": "08:00:00.0000000",
        "endTime": "17:00:00.0000000",
        "timeZone":{
            "name":"Pacific Standard Time"
        }
    },
```

**Comment by SilasKenneth** [comment]
Hi @EddieTerpan, 
Thanks for using our SDK. 
After doing some digging this doesn't look like an SDK issue since whatever you're trying to do is not supported in graph.
Refer to this closely related answer [Microsoft Learn](https://learn.microsoft.com/en-us/answers/questions/1291456/how-to-get-day-wise-working-hours-using-graph-api).
For more feedback related to Graph API kindly channel them through this [forum](https://learn.microsoft.com/en-us/answers/tags/161/ms-graph).
