### ISSUE TITLE
Unable to recognize the Microsoft/Graph/Graph import 

### ISSUE THREAD

**Issue by Shruti2481** [microsoftgraph/msgraph-sdk-php#1548]
I am using Microsoft Graph PHP SDK ^2.8 version.
I am getting error by using the below code:

```
  use Microsoft\Graph\Graph;
  $graph = new Graph();
  $graph->setAccessToken($accessToken);
```
  
  The package is unable to find the Graph class and not recognizing the  **use Microsoft\Graph\Graph;** import. 
  
  Help me find the solution, I am stuck on this.

**Comment by SilasKenneth** [comment]
Hi @Shruti2481,
Which reference are you following for using the library? (We need this to fix the reference you are using since your code is for the older version of the SDK which is not supported).
This is related to https://github.com/microsoftgraph/msgraph-sdk-php/issues/1522. 
Kindly check the link in the reply to check on how to use the SDK.
