### ISSUE TITLE
Move email between different accounts

### ISSUE THREAD

**Issue by hugcar** [microsoftgraph/msgraph-sdk-php#155]
I've been using Microsoft Graph API v1 to automate my company commercial emails. I've successfully created rules to pipe all incoming emails to my Mail Manager but now i need to move some of the emails back to my consultants inbox without having to forward it.

My app is able to read every single folder of every commercial account.

I can do almost everything above but the move. It says it can't find my folder:

ErrorToFolderNotFound

and i just got the DestinationId from another query to the API that retrieves the correct id of the destination folder.

This process between folders in the same account works flawlessly

i.e.:

ACCOUNT1 / Inbox => ACCOUNT1 / Drafts    Works

ACCOUNT1 / Inbox => ACCOUNT2 / Inbox     Doesn't work
Can anyone please help me to find a solution?

**Comment by MIchaelMainer** [comment]
Are you deleting the mails from a mailbox after Mail Manager picks them up? I'll assume you are. 

I highly suggest that you keep the mails in the consultants mailbox until it is certain that it isn't needed, at that point, delete them. I don't think hidden folders are supported at this point, but you may keep them in some retention supported folder. This way, you have a handle on the original mail and can update it from Mail Manager.

The main challenge with moving an email from Mail Manager to a mailbox is that we currently don't support full fidelity export/import. You can't simply move items between inboxes. You had to create the mail in ACCOUNT2 / Inbox with information from the mail in ACCOUNT1 / Inbox. Problem then is that the email will exist as a draft. That may or may not work for you. So this is why I say that you retain the mail in the original consultant's mailbox so that you can update it after Mail Manager is done.

**Comment by hugcar** [comment]
I should've come here sooner!!! 
Thanks Michael! 

As a matter of fact i've found all the issues you describe. i tried the copy but the creation of the copy as draft doesn't work for my purpose... 
For now, as i'm still testing, i'm not deleting the email in the pickup process. I'm adding as BCC the account that triggers my flow on every incoming email instead of redirecting and deleting the original message, so i have two copies of the email.

I've tried to follow your recomendation to parse the message and then update it in the consultant mailbox but the message id's are different in both accounts. How can i relate to the message in the consultant account from the mail manager account?

**Comment by hugcar** [comment]
Ok, i believe that i'll be able to accomplish my purpose using the field InternetMessageId instead of messageId.

Lets see......

**Comment by MIchaelMainer** [comment]
You can also add custom properties via https://docs.microsoft.com/en-us/graph/api/resources/opentypeextension?view=graph-rest-1.0. Something to consider. 

Since this isn't an issue with the client, I'll close this issue.
