### ISSUE TITLE
GraphCollectionRequest inherited GraphRequest without overriding execute method

### ISSUE THREAD

**Issue by landall** [microsoftgraph/msgraph-sdk-php#176]
I find GraphCollectionRequest is not overrided so execute method does not handle server side paging. 
It is misleading to some people. I think the code in Paging part of the wiki should become the code in GraphCollectionRequest->execute() to get all the results of a request. 
[AB#7573](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/7573)

**Comment by MIchaelMainer** [comment]
Yeah, I agree with you that it is misleading and I like your proposal for overriding the GraphCollectionRequest->execute() method with the getPage() method.

Note for future self or someone else.
GraphCollectionRequest extends GraphRequest which has execute(), which is typically how a GraphRequest is called.

**Comment by isvargasmsft** [comment]
Hello @landall, 

Thank you very much for your patience. Our efforts are currently focused on delivering a new stable version of this SDK where this issue is resolved. If you want to give it a try, we already have [a release candidate for this](https://github.com/microsoftgraph/msgraph-sdk-php/issues/943).

Please feel free to test it and share your feedback with us. 

Kind regards, 

Isaac Vargas
