### ISSUE TITLE
How can I set http_errors options of GuzzleHttp to false?

### ISSUE THREAD

**Issue by landall** [microsoftgraph/msgraph-sdk-php#232]
The default value of http_errors is true, so if a http request returns with a status code 4xx or 5xx, it will triggle 2 exceptions (GuzzleHttp\Exception\ClientException and GuzzleHttp\Exception\RequestException).
This is hard to handle it. 
How can I set this options to false to handle every situation with $response->getStatus()? 
[AB#7353](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/7353)

**Comment by PolCPP** [comment]
@landall 

I was actually doing something similar because i'm having a calendar request that randomly fails with a 412 even on the Graph explorer.

If you're doing a GraphRequest Check
https://github.com/microsoftgraph/msgraph-sdk-php/blob/dev/src/Http/GraphRequest.php

The execute method accepts passing your own guzzle instance, and if you want to know how it's built there is a protected createGuzzleClient method where you can dump and duplicate it's settings.

Not the best solution but hey, it works.

**Comment by landall** [comment]
> @landall
> 
> I was actually doing something similar because i'm having a calendar request that randomly fails with a 412 even on the Graph explorer.
> 
> If you're doing a GraphRequest Check
> https://github.com/microsoftgraph/msgraph-sdk-php/blob/dev/src/Http/GraphRequest.php
> 
> The execute method accepts passing your own guzzle instance, and if you want to know how it's built there is a protected createGuzzleClient method where you can dump and duplicate it's settings.
> 
> Not the best solution but hey, it works.

But the param should be hardcoded if I create my own Guzzle Client. This is the problem.

**Comment by MichaelBelgium** [comment]
It should be possible to add guzzle client options in general, like [delay](https://docs.guzzlephp.org/en/stable/request-options.html#delay) too. But the Graph class doesn't allow full control of the Guzzle client. 

It should be quick to implement, good idea @MIchaelMainer ? Fine if I try a PR?

**Comment by Ndiritu** [comment]
@landall @PolCPP we currently expose `setHttpErrors([true|false])` on a `GraphRequest` object

**Comment by Ndiritu** [comment]
@MichaelBelgium we support passing in your custom-configured Guzzle client when calling `execute(), executeAsync(), download() and upload()`.

In the longer term we plan to make this simpler via #438
