### ISSUE TITLE
Facilitate expected failures, specifically 404

### ISSUE THREAD

**Issue by curry684** [microsoftgraph/msgraph-sdk-php#26]
For endpoint `/me/manager` the expected result is a 404 page not found if you are the "top of the food chain". Currently this is treated as a hard error and thus causing an exception to be thrown, whilst it's expected program flow. I'd expect (in this case) a 404 to be internally handled to a `null` return value.

**Comment by cbales** [comment]
The library passes through any responses from the Graph API so that developers can decide how they would like to handle the response in cases such as you have described. Because the library is not hand-written, special casing errors can lead to unforeseen side effects when the API does not respond in a way that the library expects.
There is currently no extensibility model in place for this library, but conceivably, this behavior could be added to an "Orgainzation Helper" which would return smart defaults. In this particular instance, this seems more like a bug with the API itself, which should return null instead of an error when the user does not have a manager.

**Comment by curry684** [comment]
in RESTful logic the 404 makes sense, as it implies "Not Found". I think you can patch this on the library end, as Guzzle can be configured to disable the automatic exceptions on errors and handle it all in the library. 

http://docs.guzzlephp.org/en/stable/quickstart.html#exceptions:

> A GuzzleHttp\Exception\ClientException is thrown for 400 level errors if the http_errors request option is set to true.

**Comment by curry684** [comment]
> There is currently no extensibility model in place for this library, but conceivably, this behavior could be added to an "Orgainzation Helper" which would return smart defaults.

Would make me happy to have such features, as I also ran into the `DateTimeTimeZone` class not converting to a proper `\DateTime` or at least exposing `\DateTimeInterface`. Technically it should be possible to add such behaviors with traits or base classes during generation from metadata.

**Comment by cbales** [comment]
A counter example to the 404 issue: If you query for the children of a folder that has no items in it, you will receive an empty list of items in the response. If you query for the children of a folder that does not exist, you will receive a 404. In the first, null is within the set of acceptable responses. In the second, the user has committed an error.
The complication with the manager query is that I believe the correct way to respond to this is "null", not "404".

**Comment by curry684** [comment]
Purist REST states that an empty collection is still a collection, but empty. Hence it should return `200 OK` with `[]` as the body. In a way 404 is historically the intended `null` of the REST world, as it was originally intended and implemented.

[Reading up on the current JSON-API specs though I'm tempted to agree with you](http://jsonapi.org/format/#fetching-resources-responses):

> A server **MUST** respond to a successful request to fetch a resource collection with an array of resource objects or an empty array (`[]`) as the response document’s primary data.
> [...]
> A server **MUST** respond to a successful request to fetch an individual resource with a resource object or `null` provided as the response document’s primary data.
>
> `null` is only an appropriate response when the requested URL is one that might correspond to a single resource, but doesn’t currently.
> [...]
> A server **MUST** respond with `404 Not Found` when processing a request to fetch a single resource that does not exist, except when the request warrants a `200 OK` response with `null` as the primary data (as described above).

The words "appropriate" and "warrant" make both implementations technically *acceptable*, but specifically the case at hand seems more appropriate for a `null` indeed. Have you taken this up with the Graph core team?

**Comment by cbales** [comment]
I'll work with the relevant team(s) and follow up here.

**Comment by cbales** [comment]
The Graph API does not conform to JSON's API guidelines, but follows the OData spec:

> 9.1.1 Response Code 200 OK
A request that does not create a resource returns 200 OK if it is completed successfully and the value of the resource is not null. In this case, the response body MUST contain the value of the resource specified in the request URL.

However, we still do not want to make any assumptions about the meaning of the response and therefore will continue to return the given error instead of giving a default value.

**Comment by curry684** [comment]
Makes sense, and no argument on the rationale. But why close this issue? It was originally about the Developer eXperience (DX) of the 404, and the fact that it's perfectly defendable on the API middleware end of things doesn't mean a user of this library should have to cater for it. I still think it should intervene and return NULL to consumers.
