### ISSUE TITLE
Possible to define ca bundle path

### ISSUE THREAD

**Issue by jasverix** [microsoftgraph/msgraph-sdk-php#372]
We are using a composer package called 'composer/ca-bundle'. It has a method called `getBundledCaBundlePath()`. We are using it to make sure things works on every computer.

Guzzle has possibility to set 'verify' in their client settings, like this:
```
'verify' => CaBundle::getBundledCaBundlePath(),
```
but it is not possible to get this in through microsoft-sdk-php. `createGuzzleClient` simply does not support any modification of 'verify'. This causes this error message: "SSL certificate error: unable to get local issuer certificate".

Can it be made a possibility to set ca bundle path somehow? 
[AB#7596](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/7596)

**Comment by MIchaelMainer** [comment]
You can set this by supplying your own Guzzle client. Ideally, this could be configured for the client instead of only on a per request basis. 

Make sure you set the base url and the headers are set with a token.

```php
        $clientSettings = [
            'base_uri' => "https://graph.microsoft.com/v1.0",
            'http_errors' => true,
            'headers' => $this->getHeaderIncludingToken(),
            'verify' => CaBundle::getBundledCaBundlePath()
        ];
        $client = new Client($clientSettings);
    	$todaysEvents = $client->createRequest("GET", "/me/calendarView?startDateTime=$startTime&endDateTime=$endTime")
    						   ->setReturnType(Model\Event::class)
    						   ->execute($client);

```

Note to self, we lose benefits of any telemetry we may have in our Guzzle client and the developer needs to supply an access token. We should have a factory to produce a preconfigured Guzzle client that developers can then update with their specific options.

**Comment by MIchaelMainer** [comment]
Include work for this with #438

**Comment by isvargasmsft** [comment]
Hello @jasverix 

Thank you very much for your patience. Our [new SDK version 2.0.0-RC5](https://github.com/microsoftgraph/msgraph-sdk-php/issues/943) allows you to customize the guzzle client using the Graph client factory.

Please feel free to give it a try and share your feedback with us.

Kind regards, 

Isaac Vargas
