### ISSUE TITLE
Missing Class TimeOfDay

### ISSUE THREAD

**Issue by mvdschot** [microsoftgraph/msgraph-sdk-php#387]
version used: 1.26
php version 7.2
framework: Laravel 7.29

I'm trying to get the WorkingHours of my Outlook Calendar but gives an error:

Microsoft\Graph\Model\WorkingHours::getStartTime
vendor/microsoft/microsoft-graph/src/Model/WorkingHours.php:105

The method "getStartTime" should return a type of "TimeOfDay", but that class is missing in the package.
How can I help to get this fixed?

 
[AB#8171](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/8171)

**Comment by zengin** [comment]
Thanks @mvdschot for reporting this issue. We will need to find the right PHP type to represent these built-in types from the OData model:

```
<ComplexType Name="workingHours">
  <Property Name="daysOfWeek" Type="Collection(graph.dayOfWeek)"/>
  <Property Name="endTime" Type="Edm.TimeOfDay"/>
  <Property Name="startTime" Type="Edm.TimeOfDay"/>
  <Property Name="timeZone" Type="graph.timeZoneBase"/>
</ComplexType>
```

If there is no PHP native type, we will need to hand craft an implementation and update all the references through our generation process in https://github.com/microsoftgraph/MSGraph-SDK-Code-Generator.

Closing this because it is a subset of #369.
