### ISSUE TITLE
Is it possible to connect to Projects Web App (PWA) using graph?

### ISSUE THREAD

**Issue by marcmaalouly** [microsoftgraph/msgraph-sdk-php#471]
Hello guys,

Sorry for posting here, but I've been trying to find a solution for my problem for almost a month now and still can't prevail.

I'm trying to allow my users to sync their https://example.sharepoint.com/sites/pwa from my website and fetch a list of their projects. I still can't find a documentation or a starting point to do so.

I'm stuck on how to let the users authenticate, so I can obtain their bearer token and then use that token to authenticate on the api.

I was able to find API endpoints from: http://sharepointstore.com/2016/10/21/project-online-rest-api-list/ 

I'm using Laravel as BackEnd and VueJS as front on my website.

I would like to allow any user to connect and sync his projects.

Thank you for your kind support. 
[AB#9347](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/9347)

**Comment by lambasoft** [comment]
I'm also having the same problem @Ndiritu

**Comment by MIchaelMainer** [comment]
@marcmaalouly and @lambasoft 

Is your PWA a static site? Is the call to Microsoft Graph going to happen from VueJS or Laravel?

**Comment by MIchaelMainer** [comment]
If you're calling Microsoft Graph from the browser, take a look at what we do in [Graph Explorer](https://github.com/microsoftgraph/microsoft-graph-explorer-v4). We are using MSAL Authorization Code Flow with PKCE (deprecated Implicit Auth) to get the token as well as using the Microsoft Graph JavaScript client to make the calls to Microsoft Graph.

Here is a sample if you are going to make the call from Laravel: https://github.com/microsoftgraph/msgraph-training-phpapp

**Comment by marcmaalouly** [comment]
@MIchaelMainer Thank you for your answer, it was really helpful!

We're trying to fetch data from Microsoft Project Online, we want to fetch the projects and tasks on the project. This is where we're lost. Are you aware of any documentation or starting point to do so?

**Comment by MIchaelMainer** [comment]
@marcmaalouly Are you calling from the PWA or Laravel?

**Comment by lambasoft** [comment]
@MIchaelMainer I will answer on behalf of @marcmaalouly since we're working in the same team. 

We're trying to connect to PWA using Laravel, so technically the call is directly from Laravel.
The end objective is to be able to showcase the Microsoft Project Online tasks on a custom calendar that we created using Laravel/Blade.

**Comment by MIchaelMainer** [comment]
Got it. So I would then start with https://github.com/microsoftgraph/msgraph-training-phpapp. Make sure you star that sample so that the maintainer knows you are using it. Give feedback there as well.

On a related note, do you have a demo tenant that you can use for testing? If not, you can sign up here: https://developer.microsoft.com/en-US/microsoft-365/dev-program. Then you can use that admin account for creating the app registration like you see in the tutorial.

**Comment by lambasoft** [comment]
@MIchaelMainer We did exactly that, but it seems that Microsoft Graph does not support Project Online yet, so we can't really do it using Microsoft Graph API.
