### ISSUE TITLE
Composer issue - requires guzzlehttp/psr7 v2.0

### ISSUE THREAD

**Issue by baj84** [microsoftgraph/msgraph-sdk-php#560]
I'm unable to install because it requires `guzzlehttp/psr7 v2.0`

```
  Problem 1
    - Root composer.json requires microsoft/microsoft-graph ^1.35 -> satisfiable by microsoft/microsoft-graph[1.35.0].
    - microsoft/microsoft-graph 1.35.0 requires guzzlehttp/psr7 ^2.0 -> found guzzlehttp/psr7[dev-master, 2.0.0-beta1, 2.0.0-rc1, 2.0.0, 2.0.x-dev (alias of dev-master)] but the package is fixed to 1.8.2 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.
```

Issue is that other packages (google client api) require that guzzlehttp/psr7 be at version 1.8.

Has anyone else run into this issue?

Thanks 
[AB#10376](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/10376)

**Comment by Ndiritu** [comment]
Thanks for reporting this and my apologies that we didn't catch this scenario earlier.

Working on a fix

**Comment by hubipe** [comment]
I don't think that removing support for guzzlehttp/psr7 in version 2.0 is the correct solution. Wouldn't be better to support both versions 1.7 and 2.0 (^1.7||^2.0)? Capping guzzle to version 1.7 because other libraries have not upgraded their constraints just doesn't sound to me to be the correct approach of handling this issue...

**Comment by Ndiritu** [comment]
I agree that capping a dependency version because other libraries haven't upgraded isn't the right approach.

However, we opted for this approach to cover the arguably rare/unlikely case that a developer has been using this package while taking a direct dependency on guzzlehttp/psr7 <1.7 since we didn't previously specify a guzzlehttp/psr7 version constraint.

Keeping the deprecated `GuzzleHttp\Psr7\stream_for()` seemed to be the only way to remain fully backward compatible.

Support for guzzlehttp/psr7 2.0 will be added to the next major upgrade.
