### ISSUE TITLE
Issue when creating a user on Azure B2C using Microsoft Graph API

### ISSUE THREAD

**Issue by testlorenzospa** [microsoftgraph/msgraph-sdk-php#708]
I'm trying to build a little script PHP to integrate with the Microsoft Graph API.

I have an admin account in Azure, and have set up a new app through the portal. I've downloaded and installed the PHP SDK, and have managed to set everything up so that I can get a user successfully.

However, POSTing a new user returns me a 400 bad request:

$newUser = new User();
$newUser->setAccountEnabled(true);
$newUser->setGivenName('name');
$newUser->setSurname('surname');
$newUser->setUserPrincipalName('email@dot.com');

$password = new PasswordProfile();
$password->setPassword("pwd");
$password->setForceChangePasswordNextSignIn(false);
$newUser->setPasswordProfile($password);

$identities = new ObjectIdentity();
$identities->setSignInType("emailAddress");
$identities->setIssuer("a tenantId");
$identities->setIssuerAssignedId("email@dot.com");
$newUser->setIdentities($identities);

$user = $this->graph->createRequest('POST', '/users')
        ->attachBody($newUser)
        ->setReturnType(Model\User::class)
        ->execute();

Returns:

{"error":{"code":"BadRequest","message":"Property identities in payload has a value that does not match schema.","innerError":{"date":"2021-11-15T15:26:24","request-id":"an id","client-request-id":"an id"}}}

How can I solve this issue?

Thanks for any help.

**Comment by Ndiritu** [comment]
`$newUser->setIdentities()` should be initialised with `ObjectIdentities[]` instead of `ObjectIdentity`. [The `identities` property on a User should be an ObjectIdentity collection.](https://docs.microsoft.com/en-us/graph/api/resources/user?view=graph-rest-1.0#properties).

Handling collections of entities is a bug in v1.x of the SDK. I'll look into correcting the PHPDoc for setIdentities to hint that `ObjectIdentities[]` is required. You'll also notice that `getIdentities()` will NOT return `ObjectIdentities[]` but instead, an array containing dictionaries where each dictionary represents an ObjectIdentity.

This bug has been fixed in our `2.0.0-RC` versions which I encourage you to try out if your use-case allows.
`2.0.0` should be made stable soon.

**Comment by Ndiritu** [comment]
@testlorenzospa the fix is also available in the latest release (`1.46.0`)
