### ISSUE TITLE
Big file upload

### ISSUE THREAD

**Issue by ibrahimch** [microsoftgraph/msgraph-sdk-php#77]
Hi, while we have `UploadSession` class, `getUploadUrl`, `setUploadUrl` methods for uploading big files, but because of newbie I can't understand whole procedure, so tried normal uploading method, but returns _Maximum request length exceeded._ can anyone will explain/write the procedure/code.

**Comment by cbales** [comment]
The process for uploading large files has two steps to it: creating the upload session, and uploading batches to the session. Unfortunately the UploadSession object will not be very helpful in this instance, since it does not conform well to the metadata's description of the object. I would recommend reading the [REST documentation on large file upload](https://developer.microsoft.com/en-us/graph/docs/api-reference/v1.0/api/driveitem_createuploadsession) or asking a question on StackOverflow on how to accomplish this using a JSON payload.
